USE [master]
GO
/****** Object:  Database [BDTravel.Test]    Script Date: 15/03/2023 12:01:45 p. m. ******/
CREATE DATABASE [BDTravel.Test]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDTravel.Test', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDTravel.Test.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDTravel.Test_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDTravel.Test_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BDTravel.Test] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDTravel.Test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDTravel.Test] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BDTravel.Test] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BDTravel.Test] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BDTravel.Test] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BDTravel.Test] SET ARITHABORT OFF 
GO
ALTER DATABASE [BDTravel.Test] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BDTravel.Test] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDTravel.Test] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDTravel.Test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDTravel.Test] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BDTravel.Test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BDTravel.Test] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDTravel.Test] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BDTravel.Test] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDTravel.Test] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BDTravel.Test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDTravel.Test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDTravel.Test] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BDTravel.Test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BDTravel.Test] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDTravel.Test] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDTravel.Test] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BDTravel.Test] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BDTravel.Test] SET  MULTI_USER 
GO
ALTER DATABASE [BDTravel.Test] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BDTravel.Test] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BDTravel.Test] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BDTravel.Test] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BDTravel.Test] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BDTravel.Test] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BDTravel.Test] SET QUERY_STORE = OFF
GO
USE [BDTravel.Test]
GO
/****** Object:  Table [dbo].[TbFlights]    Script Date: 15/03/2023 12:01:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TbFlights](
	[IdFlights] [int] IDENTITY(1,1) NOT NULL,
	[IdJourney] [int] NOT NULL,
	[Origin] [varchar](3) NOT NULL,
	[Destination] [varchar](3) NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_TbFlights] PRIMARY KEY CLUSTERED 
(
	[IdFlights] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TbJourney]    Script Date: 15/03/2023 12:01:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TbJourney](
	[IdJourney] [int] IDENTITY(1,1) NOT NULL,
	[Origin] [varchar](3) NOT NULL,
	[Destination] [varchar](3) NOT NULL,
	[Price] [float] NOT NULL,
	[IdTypeRequest] [int] NOT NULL,
 CONSTRAINT [PK_TbJourney] PRIMARY KEY CLUSTERED 
(
	[IdJourney] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TbTransport]    Script Date: 15/03/2023 12:01:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TbTransport](
	[IdTransport] [int] IDENTITY(1,1) NOT NULL,
	[FlightCarrier] [varchar](3) NOT NULL,
	[FlightNumber] [int] NOT NULL,
	[IdFlights] [int] NOT NULL,
 CONSTRAINT [PK_TbTransport] PRIMARY KEY CLUSTERED 
(
	[IdTransport] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TbTypeRequest]    Script Date: 15/03/2023 12:01:46 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TbTypeRequest](
	[IdTypeRequest] [int] IDENTITY(1,1) NOT NULL,
	[NameRequest] [varchar](50) NOT NULL,
	[IntegrateCode] [int] NULL,
 CONSTRAINT [PK_TypeRequest] PRIMARY KEY CLUSTERED 
(
	[IdTypeRequest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TbTypeRequest] ON 
GO
INSERT [dbo].[TbTypeRequest] ([IdTypeRequest], [NameRequest], [IntegrateCode]) VALUES (1, N'Rutas únicas', 0)
GO
INSERT [dbo].[TbTypeRequest] ([IdTypeRequest], [NameRequest], [IntegrateCode]) VALUES (2, N'Rutas múltiples', 1)
GO
INSERT [dbo].[TbTypeRequest] ([IdTypeRequest], [NameRequest], [IntegrateCode]) VALUES (3, N'Rutas múltiples y de retorno', 2)
GO
SET IDENTITY_INSERT [dbo].[TbTypeRequest] OFF
GO
ALTER TABLE [dbo].[TbFlights]  WITH CHECK ADD  CONSTRAINT [FK_TbFlights_TbJourney] FOREIGN KEY([IdJourney])
REFERENCES [dbo].[TbJourney] ([IdJourney])
GO
ALTER TABLE [dbo].[TbFlights] CHECK CONSTRAINT [FK_TbFlights_TbJourney]
GO
ALTER TABLE [dbo].[TbJourney]  WITH CHECK ADD  CONSTRAINT [FK_TbJourney_TbTypeRequest] FOREIGN KEY([IdTypeRequest])
REFERENCES [dbo].[TbTypeRequest] ([IdTypeRequest])
GO
ALTER TABLE [dbo].[TbJourney] CHECK CONSTRAINT [FK_TbJourney_TbTypeRequest]
GO
ALTER TABLE [dbo].[TbTransport]  WITH CHECK ADD  CONSTRAINT [FK_TbTransport_TbFlights] FOREIGN KEY([IdFlights])
REFERENCES [dbo].[TbFlights] ([IdFlights])
GO
ALTER TABLE [dbo].[TbTransport] CHECK CONSTRAINT [FK_TbTransport_TbFlights]
GO
USE [master]
GO
ALTER DATABASE [BDTravel.Test] SET  READ_WRITE 
GO
